In [2]:
w=[3,4,5,6,7]
x=[9,8,7,6,4]  #vectorization; first multiply one with another and then add the list
n.dot(w,x)

158

In [1]:
import numpy as n

In [4]:
n.full((3,4,2),7)

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

In [3]:
aj=n.array([23,45,2,21,34])
print(n.exp(aj))
n.log10(aj)# to print exponential of the  value

[9.74480345e+09 3.49342711e+19 7.38905610e+00 1.31881573e+09
 5.83461743e+14]


array([1.36172784, 1.65321251, 0.30103   , 1.32221929, 1.53147892])

In [4]:
a=n.array([43,432,12])
print(a)
print(n.ndim(a))
print(a.shape)
print(a.size)

[ 43 432  12]
1
(3,)
3


In [17]:
b=n.array([[43,2,21],[43,65,76],[432,12,4354]])
print(b.shape)
print(b.size)
print(n.ndim(b))
p=b.reshape((9,1))  #array.reshape(())
print(p)

(3, 3)
9
2
[[  43]
 [   2]
 [  21]
 [  43]
 [  65]
 [  76]
 [ 432]
 [  12]
 [4354]]


In [14]:
n.arange(4,44,9)
n.linspace(3,44,45,endpoint=False,retstep=True)

(array([ 3.        ,  3.91111111,  4.82222222,  5.73333333,  6.64444444,
         7.55555556,  8.46666667,  9.37777778, 10.28888889, 11.2       ,
        12.11111111, 13.02222222, 13.93333333, 14.84444444, 15.75555556,
        16.66666667, 17.57777778, 18.48888889, 19.4       , 20.31111111,
        21.22222222, 22.13333333, 23.04444444, 23.95555556, 24.86666667,
        25.77777778, 26.68888889, 27.6       , 28.51111111, 29.42222222,
        30.33333333, 31.24444444, 32.15555556, 33.06666667, 33.97777778,
        34.88888889, 35.8       , 36.71111111, 37.62222222, 38.53333333,
        39.44444444, 40.35555556, 41.26666667, 42.17777778, 43.08888889]),
 0.9111111111111111)

# flatten to convert any to one dimension

In [39]:
print(b.flatten(order='F')) # clmn wise 
b.flatten() # row wise

[  43   43  432    2   65   12   21   76 4354]


array([  43,    2,   21,   43,   65,   76,  432,   12, 4354])

array([[  43],
       [   2],
       [  21],
       [  43],
       [  65],
       [  76],
       [ 432],
       [  12],
       [4354]])

In [25]:
c=n.array([[[43,23,3],[43,65,7],[34,23,1]],[[43,23,12],[32,54,65],[32,2,32]]])
print(c)
print(n.ndim(c))
print(c.shape)
print(c.size)

[[[43 23  3]
  [43 65  7]
  [34 23  1]]

 [[43 23 12]
  [32 54 65]
  [32  2 32]]]
3
(2, 3, 3)
18


In [26]:
print(n.zeros(5))
print(n.zeros((3,4)))
n.zeros((3,4,4)) # 3 arrays 4 rows 4 columns

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
print(n.ones(4))
print(n.ones((4,3)))
print(n.ones((3,4,2)))

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [20]:
print(n.arange(5,55,4)); #stat end step;
print(n.arange(24).reshape(4,3,2))
aa=n.arange(24).reshape(4,3,2) # 4 arrays 3 rows and 2 columns
print(n.ndim(aa))

[ 5  9 13 17 21 25 29 33 37 41 45 49 53]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
3


In [21]:
n.linspace(4,33,44,endpoint=False,retstep=True) #start end step

(array([ 4.        ,  4.65909091,  5.31818182,  5.97727273,  6.63636364,
         7.29545455,  7.95454545,  8.61363636,  9.27272727,  9.93181818,
        10.59090909, 11.25      , 11.90909091, 12.56818182, 13.22727273,
        13.88636364, 14.54545455, 15.20454545, 15.86363636, 16.52272727,
        17.18181818, 17.84090909, 18.5       , 19.15909091, 19.81818182,
        20.47727273, 21.13636364, 21.79545455, 22.45454545, 23.11363636,
        23.77272727, 24.43181818, 25.09090909, 25.75      , 26.40909091,
        27.06818182, 27.72727273, 28.38636364, 29.04545455, 29.70454545,
        30.36363636, 31.02272727, 31.68181818, 32.34090909]),
 0.6590909090909091)

In [22]:
print(n.eye(4)) # 4 rows and 4 col
print(n.eye(4,3))  # 4 rows and 3 clmns
print(n.eye(4,3,-2)) # here k value is 2 so 1 at column 2

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [23]:
k=n.random.randint(7,size=55) 
print(k)
print(len(k))
type(k)                                           # important

[5 6 4 5 1 2 0 3 3 0 6 3 1 0 4 5 1 6 3 5 2 5 6 0 3 6 2 4 3 4 5 4 1 4 5 6 6
 4 5 2 4 4 5 1 1 2 5 6 3 1 1 5 5 4 0]
55


numpy.ndarray

In [15]:
n.random.randint(4,55)

43

## shuffle array

In [37]:
l=n.random.randint(5,66,size=22)
print(l)
n.random.shuffle(l)
l

[51 57 55 63 17 37 24 53 37 59 32 22 26  8 57 21 56 26 13 27 19  7]


array([56, 57,  8, 53, 32, 55, 27, 37, 24, 57, 59, 26, 37, 26, 51, 17, 13,
        7, 19, 63, 22, 21])

## arry wth rndm

In [17]:
n.random.randint(4,444,size=(4,5,3))

array([[[124, 240, 333],
        [278, 342, 443],
        [ 23, 238, 259],
        [ 20, 150,  57],
        [357, 278, 409]],

       [[104,  85, 309],
        [ 38, 257, 296],
        [199, 282, 392],
        [241,  76, 352],
        [  9, 288, 376]],

       [[148, 400, 188],
        [ 36, 257, 289],
        [198, 384, 204],
        [228, 302, 368],
        [ 27, 368, 170]],

       [[229, 188, 372],
        [408, 192, 443],
        [ 32, 289, 355],
        [442, 216, 142],
        [ 41,  15, 197]]])

## uniform norml dstrbtn

In [29]:
#n.random.rand()
#n.random.rand(3,4)
n.random.rand(3,2,3)
#n.random.uniform()
#n.random.uniform(3,55,size=(2,4,5))
n.random.normal(3,4,size=(2,4,3))

array([[[-0.28071481, -1.72793664,  4.7250571 ],
        [ 4.46579404,  3.66648867, -2.06465376],
        [ 1.91479023,  3.95335165,  7.7431783 ],
        [ 6.87563788, -3.66487958,  4.07376154]],

       [[ 3.87621904,  0.66713643,  0.8807561 ],
        [ 0.52789196,  0.26704199,  0.67638811],
        [ 8.28355968, -4.68843066,  5.05557913],
        [-0.38779488,  7.22670591,  5.87613533]]])

In [24]:
n.random.randn(5,4,3)

array([[[ 1.18448079, -0.52387118,  0.34238749],
        [-0.89338169, -1.63353438, -0.94484221],
        [-0.4458736 ,  1.39162262, -0.89853501],
        [-0.8890284 , -1.73047398, -1.6021864 ]],

       [[-0.92995912, -1.53414264,  0.03617032],
        [ 0.8003063 ,  0.59968488,  1.49779588],
        [-0.6313376 , -1.21247826, -0.75759311],
        [ 0.44328764, -1.29940231, -0.1280579 ]],

       [[-0.33023436,  0.6095081 , -0.47000072],
        [ 0.96949574,  0.86061327, -1.27202685],
        [-0.56845249,  1.76857639, -1.0693055 ],
        [-0.51075176, -0.97473549, -1.68626173]],

       [[-1.96258793, -0.16898099, -1.09858571],
        [-0.21710564, -0.42383078, -0.61811499],
        [ 0.25907654, -0.6729527 ,  0.2673888 ],
        [ 0.388621  , -0.98492533,  0.89740186]],

       [[ 0.25133656,  1.28347162, -0.55658135],
        [-0.45518309,  0.36408636, -0.64915353],
        [ 0.49004454, -0.0853801 ,  0.96183101],
        [-0.41349638, -1.73865722, -0.16384178]]])

In [30]:
arr=n.random.randn(3,5,4)

In [31]:
arr

array([[[ 1.58403996e+00, -1.31096555e+00, -3.35658911e-01,
         -1.15323574e-01],
        [ 4.08642098e-01, -1.42108139e-01,  2.55008713e-01,
          8.88898201e-01],
        [ 5.83195729e-02,  1.02526564e+00, -1.57326486e+00,
         -3.27347358e-01],
        [ 1.09459896e-01, -7.79136939e-01,  7.23751537e-01,
          2.70262836e+00],
        [ 6.80200960e-01,  1.76113749e+00, -1.44723247e+00,
          9.05633997e-02]],

       [[ 1.73345217e+00,  6.15526667e-02,  4.48486772e-01,
         -6.47795885e-01],
        [-2.30825966e+00, -1.14678573e+00,  2.88633724e-01,
         -2.87654445e-01],
        [-3.81717530e-01, -7.73012542e-01, -8.42381991e-01,
          7.13178632e-02],
        [ 2.15182453e-01, -1.07479885e+00, -9.33535589e-02,
         -1.29841078e+00],
        [-1.33445224e+00,  3.39472225e-01,  1.55414511e+00,
         -3.32088266e-01]],

       [[ 9.07839397e-01,  8.41540685e-01, -2.17566855e-03,
          9.99556199e-01],
        [ 1.05042624e+00, -2.41173606e-

array([[[ 1.58403996e+00, -1.31096555e+00, -3.35658911e-01,
         -1.15323574e-01],
        [ 4.08642098e-01, -1.42108139e-01,  2.55008713e-01,
          8.88898201e-01],
        [ 5.83195729e-02,  1.02526564e+00, -1.57326486e+00,
         -3.27347358e-01],
        [ 1.09459896e-01, -7.79136939e-01,  7.23751537e-01,
          2.70262836e+00],
        [ 6.80200960e-01,  1.76113749e+00, -1.44723247e+00,
          9.05633997e-02]],

       [[ 9.07839397e-01,  8.41540685e-01, -2.17566855e-03,
          9.99556199e-01],
        [ 1.05042624e+00, -2.41173606e-01, -1.55427168e-01,
          5.84319122e-01],
        [-1.24619163e+00,  1.46455368e+00, -6.68382647e-01,
         -5.94699716e-02],
        [ 9.82901749e-01,  5.48583426e-01,  4.66105066e-01,
         -8.78784131e-01],
        [-1.18389404e-01,  3.86859647e-01,  8.78412684e-01,
          3.55038230e-01]],

       [[ 1.73345217e+00,  6.15526667e-02,  4.48486772e-01,
         -6.47795885e-01],
        [-2.30825966e+00, -1.14678573e+

In [7]:
ar=n.array([[[4,3,33],[43,2,1]],[[34,23,231],[4,2,11]]])
print(ar)

[[[  4   3  33]
  [ 43   2   1]]

 [[ 34  23 231]
  [  4   2  11]]]


In [9]:
print(ar.sum(axis=0),"clmn wise") #sum columns here 0 matri 0 row 0 clmn sum with 1 matrix 0 row 0 clmn....
print(ar.sum(axis=1)) #sum rows here 0 matrix 0 clm and 1 clmn sum

[[ 38  26 264]
 [ 47   4  12]] clmn wise
[[ 47   5  34]
 [ 38  25 242]]


In [29]:
arr=n.random.randn(4,4,4)
arr

array([[[-2.12222772e+00,  1.04452349e+00, -1.91296892e-01,
          6.20669570e-01],
        [ 3.43976855e-01, -1.48945900e+00, -8.60237991e-01,
          4.36665462e-01],
        [ 4.78153535e-01, -1.04921694e+00,  6.06398102e-01,
          1.77679249e+00],
        [-1.33754904e+00,  9.70320182e-01, -1.08681607e+00,
         -6.61425073e-02]],

       [[ 2.68564038e-01, -8.27172462e-01,  2.77212808e-01,
          4.64687355e-01],
        [ 3.58416499e-01, -1.14306331e+00,  8.11256741e-01,
          1.98062307e-01],
        [-4.72619178e-01, -1.52335444e+00, -5.79669977e-01,
          6.25247530e-01],
        [ 2.71294660e-01, -5.82608059e-01,  2.98728578e-01,
          1.27597132e+00]],

       [[-1.19039320e+00,  2.17120825e-01, -3.06846180e-02,
         -2.04161148e+00],
        [-2.20137722e-01, -1.19016530e+00, -7.66712493e-02,
         -2.54200440e-01],
        [-6.87823314e-02,  8.57416494e-01, -1.07459536e+00,
         -5.76044414e-01],
        [-1.77983308e+00, -2.04436256e+

In [30]:
n.hstack(arr) # in evry array all 1 rows become 1 array 2 rows become 1 array...

array([[-2.12222772e+00,  1.04452349e+00, -1.91296892e-01,
         6.20669570e-01,  2.68564038e-01, -8.27172462e-01,
         2.77212808e-01,  4.64687355e-01, -1.19039320e+00,
         2.17120825e-01, -3.06846180e-02, -2.04161148e+00,
         1.09965824e+00, -2.90582191e-01,  2.35857696e-01,
        -2.13775470e+00],
       [ 3.43976855e-01, -1.48945900e+00, -8.60237991e-01,
         4.36665462e-01,  3.58416499e-01, -1.14306331e+00,
         8.11256741e-01,  1.98062307e-01, -2.20137722e-01,
        -1.19016530e+00, -7.66712493e-02, -2.54200440e-01,
         2.74864013e-01,  6.03867908e-01,  1.73715056e+00,
         2.70658427e-01],
       [ 4.78153535e-01, -1.04921694e+00,  6.06398102e-01,
         1.77679249e+00, -4.72619178e-01, -1.52335444e+00,
        -5.79669977e-01,  6.25247530e-01, -6.87823314e-02,
         8.57416494e-01, -1.07459536e+00, -5.76044414e-01,
         1.85689263e-01, -2.08107824e+00,  1.85083475e+00,
        -7.54856855e-01],
       [-1.33754904e+00,  9.70320182e

In [31]:
n.vstack(arr) # all 1 columns become 1 array

array([[-2.12222772e+00,  1.04452349e+00, -1.91296892e-01,
         6.20669570e-01],
       [ 3.43976855e-01, -1.48945900e+00, -8.60237991e-01,
         4.36665462e-01],
       [ 4.78153535e-01, -1.04921694e+00,  6.06398102e-01,
         1.77679249e+00],
       [-1.33754904e+00,  9.70320182e-01, -1.08681607e+00,
        -6.61425073e-02],
       [ 2.68564038e-01, -8.27172462e-01,  2.77212808e-01,
         4.64687355e-01],
       [ 3.58416499e-01, -1.14306331e+00,  8.11256741e-01,
         1.98062307e-01],
       [-4.72619178e-01, -1.52335444e+00, -5.79669977e-01,
         6.25247530e-01],
       [ 2.71294660e-01, -5.82608059e-01,  2.98728578e-01,
         1.27597132e+00],
       [-1.19039320e+00,  2.17120825e-01, -3.06846180e-02,
        -2.04161148e+00],
       [-2.20137722e-01, -1.19016530e+00, -7.66712493e-02,
        -2.54200440e-01],
       [-6.87823314e-02,  8.57416494e-01, -1.07459536e+00,
        -5.76044414e-01],
       [-1.77983308e+00, -2.04436256e+00, -5.95297995e-01,
      

In [32]:
print(ar)
print('now opra')
print(n.sort(ar,axis=0),'columnwise')
print(n.sort(ar,axis=1),'rowwise')

[[ 4  3 33]
 [43  2  1]
 [ 4  2 11]]
now opra
[[ 4  2  1]
 [ 4  2 11]
 [43  3 33]] columnwise
[[ 3  4 33]
 [ 1  2 43]
 [ 2  4 11]] rowwise


In [22]:
ar[[0,2,1,0,1],[0,1,0,1,2]] #first is rows second is columns

array([ 4,  2, 43,  3,  1])

In [23]:
ar[1:,1:]

array([[ 2,  1],
       [ 2, 11]])

In [34]:
ar[2:,2:]

array([[11]])

In [37]:
ar[2:,::2] #start end step

array([[ 4, 11]])

In [26]:
aa=n.arange(24).reshape(3,4,2)

In [27]:
aa

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [28]:
aa[[2,0,1,1,0],[0,3,1,3,2],[1,1,0,1,0]] # accessing values in 3d single elements

array([17,  7, 10, 15,  4])

In [29]:
aa[1:,2:,1:] #first is which matrix second is which row third which column 

array([[[13],
        [15]],

       [[21],
        [23]]])

In [30]:
aa[0:1,3:,1:] #accessing particular value only from 3d

array([[[7]]])

In [31]:
aa[[0],[3,1,0,2,1],[1,1,1,0,0]] #accessing multiple values from one matrix only in 3d

array([7, 3, 1, 4, 2])

In [38]:
bb=n.array([[[4,43,34],[32,321,323]],[[43,23,1],[43,23,12]]])
bb.shape

(2, 2, 3)

In [39]:
#transpose of matrix from one form to another form 
bb.transpose(2,0,1)  #here 2 is 3 clmns 0 is 2 matris 1 is 2 rows in above shape

array([[[  4,  32],
        [ 43,  43]],

       [[ 43, 321],
        [ 23,  23]],

       [[ 34, 323],
        [  1,  12]]])

In [40]:
cc=n.array([[[43,32,12],[432,12,35]],[[43,32,354],[43,32,54]],[[43,32,12],[43,23,1]]])
print(cc)
cc.size

[[[ 43  32  12]
  [432  12  35]]

 [[ 43  32 354]
  [ 43  32  54]]

 [[ 43  32  12]
  [ 43  23   1]]]


18

In [41]:
cc.shape

(3, 2, 3)

In [36]:
print(cc.transpose(1,2,0))  # here 1 is 2 matrs,2 is 3 rows,0 is 3 colmns
print('second')
print(cc.transpose(2,1,0)) #here 2 is 3 matrs, 1 is 2 rows ,0 is 3 colmns

[[[ 43  43  43]
  [ 32  32  32]
  [ 12 354  12]]

 [[432  43  43]
  [ 12  32  23]
  [ 35  54   1]]]
second
[[[ 43  43  43]
  [432  43  43]]

 [[ 32  32  32]
  [ 12  32  23]]

 [[ 12 354  12]
  [ 35  54   1]]]


In [37]:
cc

array([[[ 43,  32,  12],
        [432,  12,  35]],

       [[ 43,  32, 354],
        [ 43,  32,  54]],

       [[ 43,  32,  12],
        [ 43,  23,   1]]])

In [38]:
dd=n.arange(16).reshape(4,4)

In [39]:
dd

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
n.hsplit(dd,2) # dividing of arrays into two horizontally

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [42]:
n.vsplit(dd,2) # dividing of arrays into two vertically

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [43]:
a=n.array([[43,32,12],[431,323,4]])
b=n.array([[54,322,32],[43,5,65]])
print(a,b)

[[ 43  32  12]
 [431 323   4]] [[ 54 322  32]
 [ 43   5  65]]


In [47]:
n.hstack((a,b))

array([[ 43,  32,  12,  54, 322,  32],
       [431, 323,   4,  43,   5,  65]])

In [48]:
n.concatenate((a,b),axis=1)  # row wise 1 row in one array with the another array row

array([[ 43,  32,  12,  54, 322,  32],
       [431, 323,   4,  43,   5,  65]])

In [49]:
n.vstack((a,b))

array([[ 43,  32,  12],
       [431, 323,   4],
       [ 54, 322,  32],
       [ 43,   5,  65]])

In [53]:
print(n.concatenate((a,b),axis=0)) #column wise adding


[[ 43  32  12]
 [431 323   4]
 [ 54 322  32]
 [ 43   5  65]]


In [58]:
sq=n.arange(16).reshape(4,4)

In [59]:
sq

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
n.linalg.inv(sq) #inverse  of a matrix and it must be in the square matrix form

array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

In [63]:
n.linalg.matrix_power(sq,3) #multiplication of matrix withit owns

array([[ 1680,  1940,  2200,  2460],
       [ 4880,  5620,  6360,  7100],
       [ 8080,  9300, 10520, 11740],
       [11280, 12980, 14680, 16380]])

In [64]:
n.linalg.matrix_power(sq,0)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [65]:
n.linalg.matrix_power(sq,1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
n.linalg.det(sq) #determinant of the matrix and be in sqr matrix

-2.9582283945787796e-30

In [3]:
import numpy as n
inq=list(map(int,input('enter 9 number').split( ))) 
vin=list(map(int,input('enter').split()))                          # interview question

enter 9 number34 54 34 3245 56 76 4 32 45
enter34 65 23 1 11 13 45 32 21


In [17]:
ak=n.array(inq).reshape(3,3)
mk=n.array(vin).reshape(3,3)

In [18]:
nn=n.multiply(ak,mk)
print(nn);
kk=n.array(nn).reshape(9,1)

[[1156 3510  782]
 [3245  616  988]
 [ 180 1024  945]]


In [19]:
max(kk)

array([3510])